siagen: helper.c asm.c siagen.c main.c
	gcc -o siagen main.c asm.c siagen.c helper.c

#main.o: main.c
#	gcc -O -Wall -c main.c

#siagen.o: siagen.c siagen.h
#	gcc -O -Wall -c siagen.c

#asm.o: asm.c asm.h
#	gcc -O -Wall -c asm.c

#helper.o: helper.c helper.h
#	gcc -O -Wall -c helper.c

#clean:
#	rm -f main.o siagen.o asm.o helper.o siagen

clean:
	rm -f siagen
