vlog -work work ../../ram_2_port.v  -lint -quiet
vlog -work work ../../gds_resource_table.v  -lint -quiet
vlog -work work ../../wg_resource_table.v  -lint -quiet
vlog -work work ../../resource_table.v  -lint -quiet
vlog -work work ../../resource_update_buffer.v   -lint -quiet
vlog -work work ../../global_resource_table.v  -lint -quiet
vlog -work work ../../cam_allocator.v  -lint -quiet
vlog -work work ../../allocator.v  -lint -quiet
vlog -work work ../../dis_controller.v  -lint -quiet
vlog -work work src/dis_controller_tb.v  -lint -quiet
